package app.triprank;
import org.json.*;
public class AutoSyncTest extends MergeTest {
 static JSONObject snapshot(Memory db)throws Exception{return new JSONObject().put("records",db.all()).put("pages",db.pages());}
 static JSONArray empty(){return new JSONArray();}
 static SyncEngine.Result reconcile(JSONArray base,JSONArray left,JSONArray right)throws Exception{return SyncEngine.merge(base,left,right,empty(),empty(),empty());}
 static void pure(JSONObject r)throws Exception{
  JSONArray base=new JSONArray().put(r),none=empty();JSONObject changed=new JSONObject(r.toString()).put("description","本机修改"),other=new JSONObject(r.toString()).put("description","远端修改");
  check(SyncEngine.same(reconcile(none,base,none).records,base),"initial union");check(SyncEngine.same(reconcile(base,new JSONArray().put(changed),base).records,new JSONArray().put(changed)),"offline local edit overwrites unchanged peer");check(SyncEngine.same(reconcile(base,base,new JSONArray().put(changed)).records,new JSONArray().put(changed)),"remote change pulled");
  check(reconcile(base,none,base).records.length()==0,"deletion propagates after shared baseline");SyncEngine.Result deletedEdited=reconcile(base,none,new JSONArray().put(changed));check(deletedEdited.records.length()==1&&deletedEdited.records.getJSONObject(0).getBoolean("mergeConflict"),"delete-edit preserves edited content");
  SyncEngine.Result conflict=reconcile(base,new JSONArray().put(changed),new JSONArray().put(other));check(conflict.records.length()==2&&conflict.conflicts==1,"both edited versions preserved");SyncEngine.Result reversed=reconcile(base,new JSONArray().put(other),new JSONArray().put(changed));check(SyncEngine.same(conflict.records,reversed.records),"deterministic conflict on either peer");
  check(SyncEngine.same(reconcile(base,new JSONArray().put(changed),conflict.records).records,conflict.records),"partial remote commit retry idempotent");check(SyncEngine.same(reconcile(conflict.records,conflict.records,conflict.records).records,conflict.records),"no repeated conflicts after checkpoint");
  JSONArray oldPages=new JSONArray().put(obj("{id:'sheet',name:'原名'}")),renamed=new JSONArray().put(obj("{id:'sheet',name:'新名'}"));check(SyncEngine.merge(empty(),empty(),empty(),renamed,oldPages,oldPages).pages.getJSONObject(0).getString("name").equals("新名"),"sheet rename follows changed side");
 }
 public static void main(String[] args)throws Exception{JSONObject r=obj("{id:'test',name:'项目',description:'旧描述',tier:'hang',created:1234,photos:[]}");pure(r);Memory db=new Memory();LocalServer server=new LocalServer("test".getBytes(),db,0);java.io.File backups=java.nio.file.Files.createTempDirectory("auto-backup-test").toFile();java.lang.reflect.Field backupField=LocalServer.class.getDeclaredField("mergeBackups");backupField.setAccessible(true);backupField.set(server,backups);server.start();port=server.port();try{
  String token=call("/api/login",obj("{name:'甲'}").put("code",server.code),"").data.getString("token");check(mutate(r,null,token).status==200,"initial local save");JSONObject saved=db.get(r.getString("id")),updated=new JSONObject(saved.toString()).put("description","本机修改");JSONObject payload=new JSONObject().put("app",MergeEngine.APP).put("syncProtocol",1).put("expectedRevision",db.rev).put("records",new JSONArray().put(updated)).put("pages",db.pages());
  check(call("/api/sync",payload,"").status==401,"sync authentication");check(call("/api/sync",payload,token).status==200&&db.all().length()==1&&db.get(r.getString("id")).get("description").equals(updated.get("description")),"update existing record without duplicates");check(call("/api/sync",payload,token).status==409,"stale snapshot refused");java.io.File[] files=new java.io.File(backups,"automatic").listFiles();check(files!=null&&files.length==1,"automatic pre-change backup created");JSONObject backup=new JSONObject(new String(java.nio.file.Files.readAllBytes(files[0].toPath()),java.nio.charset.StandardCharsets.UTF_8));check(SyncEngine.key(backup.getJSONArray("records").getJSONObject(0)).equals(SyncEngine.key(saved)),"backup preserves pre-sync original");
  payload.put("expectedRevision",db.rev);long before=db.rev;check(call("/api/sync",payload,token).status==200&&db.rev==before,"identical snapshot does not bump revision");
  java.lang.reflect.Field foreground=LocalServer.class.getDeclaredField("requireForeground");foreground.setAccessible(true);foreground.set(server,true);check(call("/api/sync",payload,token).status==423,"background peer refuses auto synchronization");foreground.set(server,false);
  payload.put("records",empty());check(call("/api/sync",payload,token).status==200&&db.all().length()==0,"baseline deletion applied transactionally");
  payload.put("expectedRevision",db.rev).put("records",new JSONArray().put(r).put(new JSONObject(r.toString()).put("id","bad").put("photos",new JSONArray().put("invalid"))));check(call("/api/sync",payload,token).status==400&&db.all().length()==0,"invalid snapshot leaves data unchanged");
  check(call("/api/state",null,token).data.getInt("syncProtocol")==1,"version negotiation");System.out.println("PASS "+MergeEngine.APP+": local-first three-way reconciliation, offline edits, deletions, conflicts, partial retry, rename, transactional HTTP apply, stale revision and foreground gate.");
 }finally{server.close();}}
}
