package app.triprank;
import org.json.*;import java.util.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.concurrent.*;
public class MergeTest {
 static class Memory implements LocalServer.Store{JSONArray catalog=new JSONArray().put(new JSONObject().put("id","default").put("name","默认工作页"));String catalogBefore;public JSONArray pages(){return new JSONArray(catalog.toString());}public void setPages(JSONArray p){catalog=new JSONArray(p.toString());}Map<String,String> m=new LinkedHashMap<>(),before;long rev=0,old;boolean ok;public long revision(){return rev;}public JSONArray all(){JSONArray a=new JSONArray();for(String s:m.values())a.put(new JSONObject(s));return a;}public JSONObject get(String id){return m.containsKey(id)?new JSONObject(m.get(id)):null;}public void put(JSONObject r){m.put(r.getString("id"),r.toString());}public void delete(String id){m.remove(id);}public void begin(){catalogBefore=catalog.toString();before=new LinkedHashMap<>(m);old=rev;ok=false;}public void success(){ok=true;}public void end(){if(!ok){catalog=new JSONArray(catalogBefore);m=before;rev=old;}}public void setRevision(long r){rev=r;}}
 static class Result{int status;JSONObject data;Result(int s,JSONObject d){status=s;data=d;}}
 static int port;
 static Result call(String path,JSONObject data,String token)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL("http://127.0.0.1:"+port+path).openConnection();c.setRequestProperty("Authorization","Bearer "+token);if(data!=null){c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");byte[] bytes=data.toString().getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(bytes.length);try(OutputStream out=c.getOutputStream()){out.write(bytes);}}int status=c.getResponseCode();InputStream stream=status<400?c.getInputStream():c.getErrorStream();JSONObject body=stream==null?new JSONObject():new JSONObject(new String(LocalServer.readAll(stream),StandardCharsets.UTF_8));c.disconnect();return new Result(status,body);}
 static JSONObject obj(String s){return new JSONObject(s);}
 static Result mutate(JSONObject r,Long expected,String token)throws Exception{return call("/api/mutate",new JSONObject().put("ops",new JSONArray().put(new JSONObject().put("action","put").put("record",r).put("expected",expected==null?JSONObject.NULL:expected))),token);}
 static void check(boolean b,String label){if(!b)throw new AssertionError(label);}
 public static void main(String[] args)throws Exception{Memory db=new Memory();LocalServer server=new LocalServer("test".getBytes(),db,0);java.io.File backups=java.nio.file.Files.createTempDirectory("merge-backup-test").toFile();java.lang.reflect.Field backupField=LocalServer.class.getDeclaredField("mergeBackups");backupField.setAccessible(true);backupField.set(server,backups);server.start();port=server.port();try{
 String token=call("/api/login",new JSONObject().put("code",server.code).put("name","甲"),"").data.getString("token");
 JSONObject original=obj("{id:'test',name:'景点',description:'描述',tier:'hang',created:1234,photos:[]}");original.getJSONArray("photos").put("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=");
 check(mutate(original,null,token).status==200,"initial");JSONObject changed=new JSONObject(original.toString()).put("tier","low");
 JSONArray incoming=new JSONArray().put(changed).put(new JSONObject(original.toString()).put("id","other"));
 JSONObject payload=new JSONObject().put("app",MergeEngine.APP).put("mergeProtocol",3).put("pages",db.pages()).put("expectedRevision",db.rev).put("records",incoming);
 check(call("/api/merge",payload,"").status==401,"merge requires invite authorization");Result result=call("/api/merge",payload,token);check(result.status==200&&result.data.getInt("added")==2&&result.data.getInt("conflicts")==1,"new and conflicting versions");
 check(backups.listFiles().length==1,"automatic backup created");JSONObject backup=new JSONObject(new String(java.nio.file.Files.readAllBytes(backups.listFiles()[0].toPath()),StandardCharsets.UTF_8));check(backup.getJSONArray("records").length()==1&&backup.getString("app").equals(MergeEngine.APP),"pre-merge backup contains original only");check(db.m.size()==3&&db.get("test").get("tier").equals(original.get("tier")),"original preserved");JSONObject copy=null;for(int i=0;i<db.all().length();i++){JSONObject r=db.all().getJSONObject(i);if(r.optBoolean("mergeConflict"))copy=r;}check(copy!=null&&copy.getJSONArray("photos").length()==1,"conflict photos preserved");
 check(call("/api/merge",payload,token).status==409,"stale preview rejected");payload.put("expectedRevision",db.rev);long revision=db.rev;result=call("/api/merge",payload,token);check(result.status==200&&result.data.getInt("added")==0&&db.rev==revision,"retry is idempotent");
 check(MergeEngine.plan(incoming,db.all()).additions.length()==1,"bidirectional union");JSONArray union=new JSONArray(incoming.toString());MergeEngine.Plan other=MergeEngine.plan(union,db.all());for(int i=0;i<other.additions.length();i++)union.put(other.additions.get(i));check(MergeEngine.plan(db.all(),union).additions.length()==0&&MergeEngine.plan(union,db.all()).additions.length()==0,"both peers converge despite differing local ids");
 payload.put("records",new JSONArray());check(call("/api/merge",payload,token).status==200&&db.m.size()==3,"absence never deletes");
 payload.put("records",new JSONArray().put(new JSONObject(original.toString()).put("id","fresh")).put(new JSONObject(original.toString()).put("photos",new JSONArray().put("bad"))));check(call("/api/merge",payload,token).status==400&&db.get("fresh")==null,"invalid batch rolls back");
 JSONObject edit=new JSONObject(copy.toString());edit.remove("mergeConflict");edit.remove("mergeOrigin");check(mutate(edit,copy.getLong("revision"),token).status==200&&db.get(copy.getString("id")).getBoolean("mergeConflict"),"normal edit retains conflict metadata");
 System.out.println("PASS "+MergeEngine.APP+": merge authorization, photos, conflicts, bidirectional convergence, repeat dedup, stale revision, no deletes, rollback, metadata preservation");
 }finally{server.close();}}
}
