package app.triprank;
import org.json.*;
public class SheetsTest extends MergeTest {
 static Result op(JSONObject op,String token)throws Exception{return call("/api/mutate",new JSONObject().put("ops",new JSONArray().put(op)),token);}
 static void page(Memory db,String id,String token)throws Exception{check(op(new JSONObject().put("action","pagePut").put("page",new JSONObject().put("id",id).put("name",id)).put("expectedBoard",db.rev),token).status==200,"sheet created");}
 public static void main(String[] args)throws Exception{Memory db=new Memory();LocalServer server=new LocalServer("test".getBytes(),db,0);server.start();port=server.port();try{
 String token=call("/api/login",obj("{name:'小马',userId:'aaaaaaaaaaaaaaaa'}").put("code",server.code),"").data.getString("token");page(db,"a",token);page(db,"b",token);page(db,"c",token);
 JSONObject r=obj("{id:'one',name:'星海广场',description:'共享描述',tier:'hang',workspace:'a',workspaceIds:['a','b'],created:1234,photos:[]}");r.getJSONArray("photos").put("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=");
 check(mutate(r,null,token).status==200,"one project in two sheets");check(db.m.size()==1&&Workspaces.tier(db.get("one"),"a").equals("hang")&&Workspaces.tier(db.get("one"),"b").equals("pending"),"independent initial rankings; no duplication");
 check(op(obj("{action:'move',id:'one',workspace:'b',tier:'low',beforeId:''}").put("expectedBoard",db.rev),token).status==200,"rank in B");check(Workspaces.tier(db.get("one"),"a").equals("hang")&&Workspaces.tier(db.get("one"),"b").equals("low"),"B rank does not change A");
 check(mutate(new JSONObject(r.toString()).put("description","两张表共同更新"),db.get("one").getLong("revision"),token).status==200,"shared content edit");check(Workspaces.tier(db.get("one"),"b").equals("low")&&db.get("one").getJSONArray("photos").length()==1,"edit preserves other rank and photos");
 JSONObject selection=obj("{action:'sheetSelect',workspace:'c',ids:['one']}").put("expectedBoard",db.rev);check(op(selection,token).status==200&&Workspaces.includes(db.get("one"),"c"),"include existing project through rule");check(Workspaces.tier(db.get("one"),"c").equals("pending"),"new sheet starts pending");check(op(selection,token).status==409,"stale rule rejected");
 check(op(obj("{action:'sheetSelect',workspace:'b',ids:[]}").put("expectedBoard",db.rev),token).status==200&&!Workspaces.includes(db.get("one"),"b")&&Workspaces.includes(db.get("one"),"a"),"removing membership preserves record and other sheet");
 check(op(obj("{action:'pagesCombine',target:'b',sources:['a','c']}").put("expectedBoard",db.rev),token).status==200&&db.m.size()==1&&db.pages().length()==4,"union view keeps sources and deduplicates project");check(Workspaces.includes(db.get("one"),"a")&&Workspaces.includes(db.get("one"),"b"),"source membership kept");
 check(op(obj("{action:'move',id:'one',workspace:'default',tier:'hang'}").put("expectedBoard",db.rev),token).status==409,"cannot rank excluded project");
 JSONObject legacy=obj("{id:'legacy',name:'旧景点',description:'旧描述',tier:'top',created:1234,photos:[]}");check(mutate(legacy,null,token).status==200&&Workspaces.includes(db.get("legacy"),"default")&&Workspaces.tier(db.get("legacy"),"default").equals("top"),"legacy migration preserves tier");
 JSONObject imported=new JSONObject(db.get("one").toString()).put("id","imported");check(op(new JSONObject().put("action","import").put("record",imported),token).status==200&&Workspaces.includes(db.get("imported"),"a")&&Workspaces.includes(db.get("imported"),"b"),"backup restores multi-membership");
 JSONObject merge=new JSONObject().put("app",MergeEngine.APP).put("mergeProtocol",3).put("pages",db.pages()).put("expectedRevision",db.rev).put("records",new JSONArray().put(new JSONObject(imported.toString()).put("id","merged")));check(call("/api/merge",merge,token).status==200&&Workspaces.ids(db.get("merged")).length()==3,"merge retains all memberships");merge.put("expectedRevision",db.rev);check(call("/api/merge",merge,token).data.getInt("added")==0,"multi-sheet merge idempotent");merge.put("mergeProtocol",2);check(call("/api/merge",merge,token).status==400,"old protocol cannot discard independent ranks");
 JSONObject second=new JSONObject(r.toString()).put("id","two");check(mutate(second,null,token).status==200,"second project");long aRank=Workspaces.rank(db.get("one"),"a");check(op(obj("{action:'move',id:'two',workspace:'b',tier:'pending',beforeId:'one'}").put("expectedBoard",db.rev),token).status==200,"same-tier reorder in B");check(Workspaces.rank(db.get("two"),"b")<Workspaces.rank(db.get("one"),"b")&&Workspaces.rank(db.get("one"),"a")==aRank,"same-tier ordering independent across sheets");
 check(db.get("one").getString("authorId").equals("aaaaaaaaaaaaaaaa"),"stable author identity");
 System.out.println("PASS: multi-sheet membership, independent ranks, shared photos/description, nondestructive rule changes and union, stale protection, legacy migration, backup/merge, stable author.");
 }finally{server.close();}}
}
