package app.triprank;
import android.content.*;import android.app.*;import android.os.*;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.nio.file.*;import java.util.concurrent.*;
final class AutoSync {
 static class HttpFailure extends IOException {final int code;HttpFailure(int c,String m){super(m);code=c;}}
 static volatile String status="本地保存 · 尚未扫码配对";private static Context context;private static String lt="",rt="",lastPeer="",lastCode="",lastSuccessful="";private static JSONObject local,remote;private static final java.util.concurrent.atomic.AtomicInteger generation=new java.util.concurrent.atomic.AtomicInteger();
 static void init(Context c){context=c.getApplicationContext();Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"local-first-sync");t.setDaemon(true);return t;}).scheduleWithFixedDelay(()->{try{tick();}catch(Exception e){if(e instanceof HttpFailure&&(((HttpFailure)e).code==401||((HttpFailure)e).code==403)){lt="";rt="";}local=null;remote=null;status="本地已保存 · 待同步："+(e.getMessage()==null?"连接暂不可用":e.getMessage());}},1,3,TimeUnit.SECONDS);}
 static void allowIncoming(Context c){c.getSharedPreferences("sync-node",0).edit().putBoolean("accept",true).apply();}
 static void configure(Context c,String invitation){allowIncoming(c);c.getSharedPreferences("auto-sync",0).edit().putString("invite",invitation).putBoolean("enabled",true).apply();generation.incrementAndGet();status="已配对 · 正在自动同步";}
 static void pause(Context c){c.getSharedPreferences("sync-node",0).edit().putBoolean("accept",false).apply();c.getSharedPreferences("auto-sync",0).edit().putBoolean("enabled",false).apply();generation.incrementAndGet();status="本地保存 · 自动同步已暂停";}
 static void guard(int gen)throws Exception{if(!SyncApp.visible()||generation.get()!=gen||!context.getSharedPreferences("auto-sync",0).getBoolean("enabled",false))throw new IOException("已暂停，回到前台或重新配对后继续");}
 static JSONObject request(String host,String path,String token,JSONObject data)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(host+path).openConnection();c.setConnectTimeout(5000);c.setReadTimeout(20000);c.setInstanceFollowRedirects(false);try{if(token!=null)c.setRequestProperty("Authorization","Bearer "+token);if(data!=null){byte[] bytes=data.toString().getBytes(StandardCharsets.UTF_8);if(bytes.length>32*1024*1024)throw new IOException("单次同步超过 32MB，请减少图片");c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setFixedLengthStreamingMode(bytes.length);try(OutputStream out=c.getOutputStream()){out.write(bytes);}}int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();if(in==null)throw new HttpFailure(code,"连接或配对凭证失效，请重新扫码");JSONObject response=new JSONObject(new String(LocalServer.readAll(in),StandardCharsets.UTF_8));if(code!=200)throw new HttpFailure(code,response.optString("error","连接失败"));return response;}finally{c.disconnect();}}
 static String login(String host,String code)throws Exception{JSONObject identity=new JSONObject(IdentityStore.get(context));return request(host,"/api/login",null,new JSONObject().put("code",code).put("name",identity.getString("name")).put("userId",identity.getString("id"))).getString("token");}
 static JSONObject state(String host,String token,JSONObject previous)throws Exception{JSONObject s=request(host,"/api/state?since="+(previous==null?-1:previous.getLong("revision")),token,null);if(!MergeEngine.APP.equals(s.optString("app"))||s.optInt("syncProtocol")!=1)throw new IOException("双方都需升级到 1.6 自动同步版");if(!s.optBoolean("foreground",true))throw new IOException("对方 App 不在前台或已暂停同步");return s.optBoolean("unchanged")&&previous!=null?previous:s;}
 static JSONArray pages(JSONObject s){JSONArray p=s.optJSONArray("pages");return p==null?new JSONArray():p;}
 static JSONObject payload(JSONObject receiver,SyncEngine.Result result)throws Exception{return new JSONObject().put("app",MergeEngine.APP).put("syncProtocol",1).put("expectedRevision",receiver.getLong("revision")).put("records",result.records).put("pages",result.pages);}
 private static void tick()throws Exception{
  if(!SyncApp.visible())return;if(!context.getSharedPreferences("auto-sync",0).getBoolean("enabled",false))return;if(!LedgerService.running){status="等待本机服务启动";return;}int gen=generation.get();String encoded=context.getSharedPreferences("auto-sync",0).getString("invite","");Invite invitation=Invite.parse(encoded);String peer=invitation.url;if(!invitation.ssid.isEmpty()&&ClientService.active&&!ClientService.page.isEmpty())peer="http://"+new URI(ClientService.page).getRawAuthority();String code=invitation.code;
  if(!peer.equals(lastPeer)||!code.equals(lastCode)){lt="";rt="";local=null;remote=null;lastPeer=peer;lastCode=code;}
  String own="http://127.0.0.1:8766";if(lt.isEmpty())lt=login(own,LedgerService.code);if(rt.isEmpty())rt=login(peer,code);local=state(own,lt,local);remote=state(peer,rt,remote);if(local.getString("nodeId").equals(remote.getString("nodeId")))throw new IOException("这是本机二维码，请扫描另一台手机");
  long localRev=local.getLong("revision"),remoteRev=remote.getLong("revision");String nodes=local.getString("nodeId")+":"+remote.getString("nodeId");if((nodes+":"+localRev+":"+remoteRev).equals(lastSuccessful)){status="已自动同步 · 前台每 3 秒检查";return;}
  File dir=new File(context.getFilesDir(),"sync-bases");if(!dir.exists()&&!dir.mkdirs())throw new IOException("无法保存同步进度");File checkpoint=new File(dir,MergeEngine.hash(remote.getString("nodeId"))+".json");JSONObject base=checkpoint.exists()?new JSONObject(new String(Files.readAllBytes(checkpoint.toPath()),StandardCharsets.UTF_8)):new JSONObject().put("records",new JSONArray()).put("pages",new JSONArray());
  SyncEngine.Result result=SyncEngine.merge(base.getJSONArray("records"),local.getJSONArray("records"),remote.getJSONArray("records"),pages(local),pages(remote),pages(base));guard(gen);
  boolean toRemote=!SyncEngine.same(remote.getJSONArray("records"),result.records)||!SyncEngine.canonical(pages(remote)).equals(SyncEngine.canonical(result.pages)),toLocal=!SyncEngine.same(local.getJSONArray("records"),result.records)||!SyncEngine.canonical(pages(local)).equals(SyncEngine.canonical(result.pages));
  if(toRemote){status="正在推送本机改动…";remoteRev=request(peer,"/api/sync",rt,payload(remote,result)).getLong("revision");remote=null;}guard(gen);if(toLocal){status="正在保存同行者的改动…";localRev=request(own,"/api/sync",lt,payload(local,result)).getLong("revision");local=null;}guard(gen);
  if(toRemote||toLocal||!checkpoint.exists()||!SyncEngine.same(base.getJSONArray("records"),result.records)||!SyncEngine.canonical(pages(base)).equals(SyncEngine.canonical(result.pages))){File temp=new File(dir,checkpoint.getName()+".tmp");try(FileOutputStream out=new FileOutputStream(temp)){out.write(new JSONObject().put("records",result.records).put("pages",result.pages).toString().getBytes(StandardCharsets.UTF_8));out.getFD().sync();}Files.move(temp.toPath(),checkpoint.toPath(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}
  lastSuccessful=nodes+":"+localRev+":"+remoteRev;status=result.conflicts>0?"已同步 · 有冲突副本，请核对":"已自动同步 · 前台每 3 秒检查";
 }
 static void openLocal(Activity a){try{if(!LedgerService.running)a.startForegroundService(new Intent(a,LedgerService.class));}catch(Exception e){Toast.makeText(a,"本机服务启动失败",Toast.LENGTH_LONG).show();return;}final int[] tries={0};Handler h=new Handler(Looper.getMainLooper());h.post(new Runnable(){public void run(){if(a.isFinishing())return;if(LedgerService.running){WebActivity.open(a,"http://127.0.0.1:8766/#join="+LedgerService.code);a.finish();}else if(tries[0]++<30)h.postDelayed(this,200);else Toast.makeText(a,"本机数据未就绪，请返回首页重试",Toast.LENGTH_LONG).show();}});}
}
