package app.triprank;
import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.net.*;import android.net.wifi.*;import android.os.*;import java.net.*;
public class ClientService extends Service {
 static volatile String status="",page="",failure="";static volatile boolean active=false;
 private ConnectivityManager cm;private ConnectivityManager.NetworkCallback callback;private LocalProxy proxy;private PowerManager.WakeLock wake;private boolean destroyed;private Invite invite;private boolean available=false;
 public int onStartCommand(Intent intent,int flags,int id){if(intent!=null&&"STOP".equals(intent.getAction())){stopSelf();return START_NOT_STICKY;}if(active)return START_NOT_STICKY;active=true;failure="";page="";status="正在请求连接热点…";
 try{if(Build.VERSION.SDK_INT<29)throw new Exception("自动连接需要 Android 10 或更高版本。请先手动连热点，再扫描主机的页面二维码。");invite=Invite.parse(intent.getStringExtra("invite"));if(invite.ssid.isEmpty())throw new Exception("未提供热点名称");NotificationManager manager=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);manager.createNotificationChannel(new NotificationChannel("trip-client","加入榜单连接状态",NotificationManager.IMPORTANCE_LOW));PendingIntent open=PendingIntent.getActivity(this,31,new Intent(this,JoinActivity.class),PendingIntent.FLAG_IMMUTABLE);PendingIntent stop=PendingIntent.getService(this,32,new Intent(this,ClientService.class).setAction("STOP"),PendingIntent.FLAG_IMMUTABLE);Notification note=new Notification.Builder(this,"trip-client").setSmallIcon(R.drawable.icon).setContentTitle("旅途排排榜连接中").setContentText("维持热点连接，点击返回榜单。").setContentIntent(open).setOngoing(true).addAction(new Notification.Action.Builder(null,"断开",stop).build()).build();startForeground(2,note,ServiceInfo.FOREGROUND_SERVICE_TYPE_CONNECTED_DEVICE);
 cm=(ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);WifiNetworkSpecifier.Builder builder=new WifiNetworkSpecifier.Builder().setSsid(invite.ssid);if(invite.security.equals("WPA2"))builder.setWpa2Passphrase(invite.password);else if(invite.security.equals("WPA3"))builder.setWpa3Passphrase(invite.password);NetworkRequest request=new NetworkRequest.Builder().addTransportType(NetworkCapabilities.TRANSPORT_WIFI).removeCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET).setNetworkSpecifier(builder.build()).build();
 wake=((PowerManager)getSystemService(POWER_SERVICE)).newWakeLock(PowerManager.PARTIAL_WAKE_LOCK,"triprank:guest-connection");wake.acquire();
 callback=new ConnectivityManager.NetworkCallback(){public void onAvailable(Network network){if(available||destroyed)return;available=true;status="热点已连接，正在打开榜单…";new Thread(()->{try{HttpURLConnection check=(HttpURLConnection)network.openConnection(new URL(invite.url+"/api/state"));try{check.setConnectTimeout(8000);check.setReadTimeout(8000);check.setInstanceFollowRedirects(false);int result=check.getResponseCode();if(result!=401&&result!=200)throw new Exception("主机地址不可用，请重新生成二维码");}finally{check.disconnect();}synchronized(ClientService.this){if(destroyed)return;proxy=new LocalProxy(network,invite.url);proxy.start();page="http://127.0.0.1:"+proxy.port()+"/#join="+invite.code;status="已连接「"+invite.ssid+"」，可以进入榜单";}}catch(Exception e){failed("已连接热点，但无法打开主机。请检查主机共享是否开启、二维码地址是否正确。");}},"triprank-connect").start();}public void onUnavailable(){failed("连接被取消或热点不可用。请确认主机开启热点、填写的名称与密码正确，然后重新扫码。");}public void onLost(Network network){synchronized(ClientService.this){available=false;page="";if(proxy!=null){proxy.close();proxy=null;}status="连接中断，等待热点恢复；本机可继续编辑";}}};
 cm.requestNetwork(request,callback,60000);
 }catch(Exception e){failed(e.getMessage()==null?"无法请求热点连接，请检查 Wi-Fi 和权限":e.getMessage());}return START_NOT_STICKY;}
 private void failed(String text){if(destroyed)return;failure=text;status=text;page="";stopSelf();}
 public synchronized void onDestroy(){destroyed=true;active=false;page="";if(callback!=null&&cm!=null)try{cm.unregisterNetworkCallback(callback);}catch(Exception ignored){}if(proxy!=null)proxy.close();if(wake!=null&&wake.isHeld())wake.release();stopForeground(true);super.onDestroy();}
 public IBinder onBind(Intent i){return null;}
}
