package app.triprank;
import android.app.*;import android.os.*;import android.content.*;import android.provider.Settings;import android.widget.*;
public class JoinActivity extends Activity {
 private boolean merging;private TextView state;private Button open;private Invite invite;private String encoded;private boolean foreground,launched=false,followService=false;private final Handler handler=new Handler(Looper.getMainLooper());
 private final Runnable tick=new Runnable(){public void run(){if(followService)state.setText(ClientService.status.isEmpty()?"等待连接…":ClientService.status);open.setEnabled(ClientService.active&&!ClientService.page.isEmpty());if(followService&&foreground&&!launched&&ClientService.active&&!ClientService.page.isEmpty())openPage();handler.postDelayed(this,700);}};
 public void onCreate(Bundle b){super.onCreate(b);merging=getIntent().getBooleanExtra("merge",false);ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(26,72,26,40);scroll.addView(box);setContentView(scroll);scroll.setOnApplyWindowInsetsListener((v,i)->{box.setPadding(26,24+i.getSystemWindowInsetTop(),26,24+i.getSystemWindowInsetBottom());return i;});TextView title=new TextView(this);title.setText("返回 / 加入榜单");title.setTextSize(26);box.addView(title);state=new TextView(this);state.setTextSize(17);state.setPadding(0,24,0,24);box.addView(state);open=new Button(this);open.setText("进入已连接的榜单");open.setOnClickListener(v->openPage());box.addView(open);Button retry=new Button(this);retry.setText("重新尝试连接");retry.setOnClickListener(v->{if(ClientService.active){Toast.makeText(this,"连接进行中，请等待系统确认或先断开",Toast.LENGTH_SHORT).show();return;}launched=false;begin();});box.addView(retry);Button rescan=new Button(this);rescan.setText("重新扫码 / 返回首页");rescan.setOnClickListener(v->{startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));finish();});box.addView(rescan);Button stop=new Button(this);stop.setText("断开连接并返回");stop.setOnClickListener(v->{AutoSync.pause(this);stopService(new Intent(this,ClientService.class));finish();});box.addView(stop);TextView info=new TextView(this);info.setText("已记住最近一次加入的信息。连接已断开时会尝试重新连接；热点名称或主机地址变化时，请重新扫码。\n首次连接仍可能需要系统 Wi-Fi 确认。Android 10–12 可能还需打开定位开关。 ");info.setPadding(0,20,0,0);box.addView(info);Button settings=new Button(this);settings.setText("打开 Wi-Fi / 网络设置");settings.setOnClickListener(v->startActivity(new Intent(Settings.ACTION_WIRELESS_SETTINGS)));box.addView(settings);
  String incoming=getIntent().getStringExtra("invite");if(incoming==null&&getIntent().getData()!=null)incoming=getIntent().getData().toString();String saved=getSharedPreferences("joined-session",MODE_PRIVATE).getString("invite",null);encoded=incoming!=null?incoming:saved;
  try{if(encoded!=null)invite=Invite.parse(encoded);if(incoming!=null&&ClientService.active&&saved!=null&&!incoming.equals(saved)){state.setText("正在连接另一个榜单，请先断开再扫描新邀请。");return;}
   if(invite!=null)getSharedPreferences("joined-session",MODE_PRIVATE).edit().putString("invite",encoded).apply();
   JoinRoute.Target route=JoinRoute.decide(ClientService.active,!ClientService.page.isEmpty(),invite!=null,invite!=null&&!invite.ssid.isEmpty());
   switch(route){case READY:followService=true;break;case WAITING:followService=true;state.setText("正在恢复已有连接…");break;case DIRECT:launch(invite.page(),false);break;case RECONNECT:begin();break;case MISSING:state.setText("还没有保存的加入记录。请返回首页扫码一次，之后可从这里直接返回。");break;}
  }catch(Exception e){state.setText("邀请无法使用，请重新扫码："+e.getMessage());}
 }
 private void launch(String page,boolean disconnect){AutoSync.configure(this,encoded);AutoSync.openLocal(this);}

 private void begin(){if(invite==null){state.setText("没有保存的加入记录，请返回首页重新扫码。");return;}if(invite.ssid.isEmpty()){launch(invite.page(),false);return;}if(Build.VERSION.SDK_INT<29){state.setText("自动连接需要 Android 10+。请先连接热点，再扫描主机的页面二维码。");return;}String permission=Build.VERSION.SDK_INT>=33?"android.permission.NEARBY_WIFI_DEVICES":"android.permission.ACCESS_FINE_LOCATION";if(checkSelfPermission(permission)!=0){requestPermissions(new String[]{permission},8);return;}followService=true;ClientService.status="正在恢复热点连接，请留意系统提示…";ClientService.failure="";try{startForegroundService(new Intent(this,ClientService.class).putExtra("invite",encoded));}catch(Exception e){followService=false;state.setText("无法启动连接："+e.getMessage());}}
 public void onRequestPermissionsResult(int r,String[] p,int[] result){super.onRequestPermissionsResult(r,p,result);if(r==8){if(result.length>0&&result[0]==0)begin();else {followService=false;state.setText("未允许附近 Wi-Fi 权限。请重新尝试，或先手动连接热点再扫描页面二维码。");}}}
 private void openPage(){if(ClientService.active&&!ClientService.page.isEmpty()){launched=true;launch(ClientService.page,true);}}
 public void onResume(){super.onResume();foreground=true;handler.post(tick);}public void onPause(){foreground=false;handler.removeCallbacks(tick);super.onPause();}
}
