package app.triprank;
import android.net.Network;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import org.json.*;
/** Loopback relay keeps the browser's traffic on the Wi-Fi network approved for this app. */
final class LocalProxy {
 interface Opener {HttpURLConnection open(URL url)throws IOException;}
 private final ServerSocket listener;private final String remote;private final Opener opener;private volatile boolean alive=true;
 private final ThreadPoolExecutor workers=new ThreadPoolExecutor(2,4,30,TimeUnit.SECONDS,new ArrayBlockingQueue<Runnable>(12));
 LocalProxy(Network network,String remote)throws Exception{this(url->(HttpURLConnection)network.openConnection(url),remote);}
 LocalProxy(Opener source,String remote)throws Exception{opener=source;this.remote=remote;listener=new ServerSocket(0,16,InetAddress.getByName("127.0.0.1"));}
 int port(){return listener.getLocalPort();}
 void start(){new Thread(()->{while(alive){try{Socket s=listener.accept();s.setSoTimeout(30000);try{workers.execute(()->handle(s));}catch(RejectedExecutionException e){s.close();}}catch(IOException ignored){}}},"triprank-local-relay").start();}
 void close(){alive=false;try{listener.close();}catch(Exception ignored){}workers.shutdown();}
 private void handle(Socket client){try(Socket s=client){OutputStream out=s.getOutputStream();try{InputStream in=new BufferedInputStream(s.getInputStream());String[] first=LocalServer.line(in).split(" ");if(first.length!=3)throw new Exception("请求无效");String method=first[0],path=first[1];boolean valid=method.equals("GET")&&(path.equals("/")||path.matches("/api/state(\\?since=-?[0-9]+)?"))||method.equals("POST")&&(path.equals("/api/login")||path.equals("/api/mutate")||path.equals("/api/merge")||path.equals("/api/sync"));if(!valid){LocalServer.json(out,404,new JSONObject().put("error","页面不存在"));return;}Map<String,String> h=new HashMap<>();int size=0;for(;;){String line=LocalServer.line(in);if(line.isEmpty())break;if((size+=line.length())>16384)throw new Exception();int split=line.indexOf(':');if(split<1)throw new Exception();String key=line.substring(0,split).toLowerCase(Locale.ROOT);if(h.containsKey(key))throw new Exception();h.put(key,line.substring(split+1).trim());}
 if(!("127.0.0.1:"+port()).equals(h.get("host"))){LocalServer.json(out,403,new JSONObject().put("error","只允许本机浏览器访问"));return;}
 if(h.containsKey("origin")&&!h.get("origin").equals("http://127.0.0.1:"+port())){LocalServer.json(out,403,new JSONObject().put("error","不允许跨站访问"));return;}
 byte[] body=null;if(method.equals("POST")){if(!h.getOrDefault("content-type","").split(";")[0].equals("application/json")||h.containsKey("transfer-encoding"))throw new Exception();int length=Integer.parseInt(h.getOrDefault("content-length","0"));if(length<=0||length>32*1024*1024){LocalServer.json(out,413,new JSONObject().put("error","单次请求上限 32MB"));return;}body=new byte[length];int at=0,n;while(at<length&&(n=in.read(body,at,length-at))>0)at+=n;if(at!=length)throw new Exception();}
 HttpURLConnection c=opener.open(new URL(remote+path));try{c.setConnectTimeout(10000);c.setReadTimeout(30000);c.setInstanceFollowRedirects(false);c.setRequestMethod(method);c.setRequestProperty("Authorization",h.getOrDefault("authorization",""));if(body!=null){c.setRequestProperty("Origin",remote);c.setRequestProperty("Content-Type","application/json");c.setDoOutput(true);c.setFixedLengthStreamingMode(body.length);try(OutputStream upstream=c.getOutputStream()){upstream.write(body);}}int status=c.getResponseCode();if(status>=300&&status<400)throw new IOException("主机地址变化，请重新扫码");String type=c.getContentType();if(type==null||type.indexOf('\r')>=0||type.indexOf('\n')>=0)type="application/json";InputStream response=status>=400?c.getErrorStream():c.getInputStream();byte[] bytes=response==null?new byte[0]:LocalServer.readAll(response);LocalServer.send(out,status,type,bytes);}finally{c.disconnect();}
 }catch(Exception e){LocalServer.json(out,503,new JSONObject().put("error","无法连接主机，请确认热点、主机 App 与当前邀请仍然有效"));}}catch(Exception ignored){}}
}
