package app.triprank;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.net.Uri;import android.provider.Settings;import android.text.InputType;import android.view.*;import android.widget.*;import java.net.*;import java.util.*;import com.google.zxing.*;import com.google.zxing.common.BitMatrix;
public class MainActivity extends Activity {
 private TextView state;private Button start,open,inviteButton;private final Handler handler=new Handler(Looper.getMainLooper());private final Runnable refresh=new Runnable(){public void run(){update();handler.postDelayed(this,1000);}};
 private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 private TextView text(LinearLayout box,String s,int size,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(Color.rgb(30,37,63));t.setPadding(0,dp(9),0,dp(9));if(bold)t.setTypeface(null,1);box.addView(t);return t;}
 private Button button(LinearLayout box,String label,View.OnClickListener action){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(16);b.setOnClickListener(action);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.topMargin=dp(9);box.addView(b,p);return b;}
 public void onCreate(Bundle b){super.onCreate(b);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(Color.rgb(246,247,251));LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(24),dp(28),dp(24),dp(30));scroll.addView(box);setContentView(scroll);scroll.setOnApplyWindowInsetsListener((v,i)->{box.setPadding(dp(24),dp(18)+i.getSystemWindowInsetTop(),dp(24),dp(24)+i.getSystemWindowInsetBottom());return i;});text(box,"旅途排排榜",30,true);text(box,"扫码连热点，直接一起排",17,false);state=text(box,"共享服务未启动",16,true);
 text(box,"我是主机",18,true);start=button(box,"启动共享榜单",v->{if(ClientService.active){error("请先断开已加入的榜单，再启动自己的共享。");return;}try{startForegroundService(new Intent(this,LedgerService.class));state.setText("正在启动…");}catch(Exception e){error(e.getMessage());}});
 open=button(box,"打开我的榜单（免输码）",v->{if(LedgerService.running)browse("http://127.0.0.1:8766/#join="+LedgerService.code);});
 inviteButton=button(box,"生成二维码，邀请同行者",v->configureInvite());
 button(box,"打开个人热点 / 网络设置",v->startActivity(new Intent(Settings.ACTION_WIRELESS_SETTINGS)));
 button(box,"本地编辑 / 同步备份",v->startActivity(new Intent(this,MergeActivity.class)));button(box,"扫码配对 · 前台自动同步",v->{if(ClientService.active){error("请先断开现有加入连接，再扫码配对。");return;}startActivityForResult(new Intent(this,ScanActivity.class),11);});text(box,"我要加入",18,true);button(box,"扫码配对另一台手机",v->{if(ClientService.active){error("请先断开已有配对连接，再扫描新的邀请。");return;}startActivityForResult(new Intent(this,ScanActivity.class),10);});button(box,"返回已加入的榜单",v->{startActivity(new Intent(this,JoinActivity.class));});
 button(box,"停止共享 / 断开加入",v->new AlertDialog.Builder(this).setTitle("结束当前连接？").setMessage("已保存的景点会保留。若你是主机，其他人将无法继续访问。") .setNegativeButton("取消",null).setPositiveButton("结束",(d,w)->{AutoSync.pause(this);stopService(new Intent(this,LedgerService.class));stopService(new Intent(this,ClientService.class));update();}).show());
 text(box,"自动同步（实验性）",19,true);text(box,"每个人编辑本机数据。扫码配对一次后，双方 App 在前台且连接可用时，每 3 秒自动交换改动；断线继续本地保存，恢复连接后补同步。修改冲突保留副本；已同步记录的删除也会传播。二维码持续有效，请只向同行者展示。",15,false);text(box,"怎样扫码连接",19,true);text(box,"主机：开启个人热点 → 启动共享 → 填一次热点名称与密码 → 展示二维码。\n同行者：安装本 App → 扫码 → 接受系统 Wi-Fi 连接提示 → 自动进入榜单，不用再输入访问码。",15,false);text(box,"自动连接适用于 Android 10+。无需 App 的参与者（含 iPhone）可以先连接热点，再用普通相机扫描“页面二维码”，直接入场；本 App 扫码会在应用内打开。",14,false);text(box,"二维码包含热点密码和入场凭证，只向同行者展示。邀请持续有效，景点仍保留。请允许通知与后台运行；定期在页面导出备份，卸载 App 会删除本机榜单。",14,false);
 if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=0)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},4);
 }
 private void configureInvite(){if(!LedgerService.running)return;ArrayList<String> urls=addressList();if(urls.isEmpty()){error("还没有检测到局域网地址。请先开启个人热点或连接 Wi-Fi，再生成二维码。");return;}ScrollView scroll=new ScrollView(this);LinearLayout form=new LinearLayout(this);form.setOrientation(1);form.setPadding(dp(22),dp(12),dp(22),dp(12));scroll.addView(form);text(form,"填写当前热点的信息；App 不会更改你的系统热点。",14,false);text(form,"主机地址（多个地址时选热点对应地址）",12,true);Spinner address=new Spinner(this);address.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,urls));form.addView(address);SharedPreferences prefs=getSharedPreferences("hotspot-invite",MODE_PRIVATE);text(form,"个人热点名称",13,true);EditText ssid=new EditText(this);ssid.setSingleLine(true);ssid.setHint("与系统热点设置完全一致");ssid.setText(prefs.getString("ssid",""));form.addView(ssid);text(form,"热点密码",13,true);EditText password=new EditText(this);password.setSingleLine(true);password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);password.setText(prefs.getString("password",""));form.addView(password);text(form,"加密方式（与热点设置一致）",13,true);Spinner security=new Spinner(this);security.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"WPA2 / WPA2-WPA3 兼容","WPA3","无密码"}));security.setSelection(prefs.getInt("security",0));form.addView(security);text(form,"热点名称和密码保存在本机应用私有设置中。若同行者已连好热点，可只生成页面二维码。",12,false);
 AlertDialog dialog=new AlertDialog.Builder(this).setTitle("创建扫码邀请").setView(scroll).setPositiveButton("生成一体化二维码",null).setNeutralButton("仅页面二维码",null).setNegativeButton("取消",null).create();dialog.setOnShowListener(d->{dialog.getButton(-1).setOnClickListener(v->{try{Invite i=new Invite();i.url=address.getSelectedItem().toString();i.code=LedgerService.code;i.ssid=ssid.getText().toString();i.password=password.getText().toString();i.security=new String[]{"WPA2","WPA3","OPEN"}[security.getSelectedItemPosition()];if(i.ssid.isEmpty())throw new Exception("请输入热点名称");if(i.security.equals("OPEN"))i.password="";i.validate();prefs.edit().putString("ssid",i.ssid).putString("password",i.password).putInt("security",security.getSelectedItemPosition()).apply();dialog.dismiss();showQR(i,true);}catch(Exception e){error(e.getMessage());}});dialog.getButton(-3).setOnClickListener(v->{try{Invite i=new Invite();i.url=address.getSelectedItem().toString();i.code=LedgerService.code;i.validate();dialog.dismiss();showQR(i,false);}catch(Exception e){error(e.getMessage());}});});dialog.show();}
 private void showQR(Invite i,boolean combined){AutoSync.allowIncoming(this);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(16),dp(12),dp(16),dp(12));TextView explanation=text(box,"",15,true);ImageView image=new ImageView(this);image.setBackgroundColor(Color.WHITE);int size=Math.min(getResources().getDisplayMetrics().widthPixels-dp(80),dp(320));box.addView(image,new LinearLayout.LayoutParams(-1,size));TextView note=text(box,"二维码是加入凭证，请仅向同行者展示。",12,false);final boolean[] mode={combined};Runnable draw=()->{try{String payload=mode[0]?i.encode():i.page();Map<EncodeHintType,Object> hints=new EnumMap<>(EncodeHintType.class);hints.put(EncodeHintType.CHARACTER_SET,"UTF-8");hints.put(EncodeHintType.MARGIN,4);BitMatrix qr=new MultiFormatWriter().encode(payload,BarcodeFormat.QR_CODE,720,720,hints);Bitmap bitmap=Bitmap.createBitmap(720,720,Bitmap.Config.RGB_565);int[] pixels=new int[720*720];for(int y=0;y<720;y++)for(int x=0;x<720;x++)pixels[y*720+x]=qr.get(x,y)?Color.BLACK:Color.WHITE;bitmap.setPixels(pixels,0,720,0,0,720,720);image.setImageBitmap(bitmap);explanation.setText(mode[0]?"用旅途排排榜 App 扫码\n连接「"+i.ssid+"」并自动入场":"已连接热点：用普通相机扫码\n直接打开榜单，无需输访问码");note.setText(i.url+"\n保持双方 App 在前台，自动同步本机数据。");}catch(Exception e){error(e.getMessage());}};draw.run();if(!i.ssid.isEmpty())button(box,"切换：一体化 / 页面二维码",v->{mode[0]=!mode[0];draw.run();});new AlertDialog.Builder(this).setTitle("邀请同行者").setView(box).setPositiveButton("完成",null).show();}
 private void browse(String url){WebActivity.open(this,url);}

 private void error(String s){new AlertDialog.Builder(this).setMessage(s==null?"操作失败，请重试":s).setPositiveButton("知道了",null).show();}
 private void update(){boolean on=LedgerService.running;state.setText(on?AutoSync.status:ClientService.active?"已开启加入连接 · "+ClientService.status:LedgerService.error.isEmpty()?"共享服务未启动":"共享服务："+LedgerService.error);open.setEnabled(on);inviteButton.setEnabled(on);start.setEnabled(!on&&!ClientService.active);}
 static ArrayList<String> addressList(){ArrayList<String> a=new ArrayList<>();try{Enumeration<NetworkInterface> es=NetworkInterface.getNetworkInterfaces();while(es.hasMoreElements()){NetworkInterface n=es.nextElement();if(!n.isUp()||n.isLoopback())continue;Enumeration<InetAddress> ips=n.getInetAddresses();while(ips.hasMoreElements()){InetAddress ip=ips.nextElement();if(ip instanceof Inet4Address&&!ip.isLoopbackAddress()&&ip.isSiteLocalAddress())a.add("http://"+ip.getHostAddress()+":8766");}}}catch(Exception ignored){}return a;}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if((r==10||r==11)&&result==RESULT_OK&&data!=null)startActivity(new Intent(this,JoinActivity.class).putExtra("invite",data.getStringExtra("invite")).putExtra("merge",r==11));}
 public void onResume(){super.onResume();handler.post(refresh);}public void onPause(){handler.removeCallbacks(refresh);super.onPause();}
}
