package app.triprank;
import android.app.*;import android.os.*;import android.content.*;import android.widget.*;import org.json.*;import java.net.*;import java.io.*;import java.nio.charset.StandardCharsets;
public class MergeActivity extends Activity {
 private TextView status;private Button preview,merge;private JSONObject local,remote;private String remoteBase,remoteCode,lt,rt;private boolean busy=false,remoteApplied=false;private File exportFile;
 private final String base="http://127.0.0.1:8766";
 public void onCreate(Bundle b){super.onCreate(b);ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(28,70,28,40);scroll.addView(box);setContentView(scroll);
 TextView title=new TextView(this);title.setText("本机数据 / 同步备份");title.setTextSize(26);box.addView(title);TextView help=new TextView(this);help.setText("App 内始终编辑本机数据。首页扫码配对一次后，双方 App 在前台且连接可用时自动同步；断线继续本地保存，恢复连接后补同步。冲突保留副本，已同步记录的删除会传播。自动同步前保留最近 5 次本机备份，可在下方导出。功能仍属实验性。");box.addView(help);status=new TextView(this);status.setPadding(0,24,0,24);box.addView(status);
 preview=button(box,"预览双方变化",v->work(false));merge=button(box,"确认双向合并一次",v->new AlertDialog.Builder(this).setTitle("执行实验性合并？").setMessage("将按当前预览向双方写入数据，先备份再合并。冲突副本需要手动整理。").setNegativeButton("取消",null).setPositiveButton("合并",(d,w)->work(true)).show());merge.setEnabled(false);
 button(box,"打开本机数据",v->{if(!busy&&LedgerService.running){WebActivity.open(this,base+"/#join="+LedgerService.code);finish();}});
 button(box,"导出合并前备份",v->{File dir=new File(getFilesDir(),"merge-backups");java.util.ArrayList<File> available=new java.util.ArrayList<>();File[] top=dir.listFiles();if(top!=null)for(File f:top){if(f.isFile())available.add(f);else if(f.getName().equals("automatic")){File[] children=f.listFiles();if(children!=null)for(File child:children)if(child.isFile())available.add(child);}}File[] files=available.toArray(new File[0]);if(files==null||files.length==0){status.setText("暂无自动备份；本机发生合并写入时会自动备份。");return;}java.util.Arrays.sort(files,(a,c)->Long.compare(c.lastModified(),a.lastModified()));String[] names=new String[files.length];for(int i=0;i<files.length;i++)names[i]=new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss",java.util.Locale.ROOT).format(new java.util.Date(files[i].lastModified()));new AlertDialog.Builder(this).setTitle("选择合并前备份").setItems(names,(d,w)->{exportFile=files[w];startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,MergeEngine.APP+"-"+exportFile.getName()),21);}).show();});
 try{String page=getIntent().getStringExtra("page");if(page!=null){URI u=new URI(page);remoteBase="http://"+u.getRawAuthority();remoteCode=u.getFragment().substring(5);status.setText("已连接。点击预览，不会自动写入。");}else{preview.setVisibility(android.view.View.GONE);merge.setVisibility(android.view.View.GONE);status.setText("本机可离线编辑。首页扫码配对后，前台自动同步，无需手动合并。");}if(!LedgerService.running)startForegroundService(new Intent(this,LedgerService.class));}catch(Exception e){status.setText("无法准备合并："+e.getMessage());preview.setEnabled(false);}
 }
 private Button button(LinearLayout b,String s,android.view.View.OnClickListener l){Button x=new Button(this);x.setText(s);x.setOnClickListener(l);b.addView(x);return x;}
 private JSONObject request(String host,String path,String token,JSONObject data)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(host+path).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(60000);c.setInstanceFollowRedirects(false);try{if(token!=null)c.setRequestProperty("Authorization","Bearer "+token);if(data!=null){byte[] bytes=data.toString().getBytes(StandardCharsets.UTF_8);if(bytes.length>32*1024*1024)throw new IOException("数据超过单次 32MB 上限，请减少图片后重试");c.setRequestMethod("POST");c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");c.setFixedLengthStreamingMode(bytes.length);try(OutputStream out=c.getOutputStream()){out.write(bytes);}}int code=c.getResponseCode();InputStream in=code<400?c.getInputStream():c.getErrorStream();if(in==null)throw new IOException("连接或凭证已失效，请重新扫码");JSONObject result=new JSONObject(new String(LocalServer.readAll(in),StandardCharsets.UTF_8));if(code!=200)throw new IOException(result.optString("error","连接失败"));return result;}finally{c.disconnect();}}
 private String login(String host,String code)throws Exception{return request(host,"/api/login",null,new JSONObject().put("code",code).put("name",new JSONObject(IdentityStore.get(this)).getString("name")).put("userId",new JSONObject(IdentityStore.get(this)).getString("id"))).getString("token");}
 private void check(JSONObject s)throws Exception{if(!MergeEngine.APP.equals(s.optString("app"))||s.optInt("mergeProtocol")!=3)throw new IOException("双方都需要安装同一应用的 1.5 或更新版");}
 private JSONObject payload(JSONObject receiver,JSONObject sender)throws Exception{return new JSONObject().put("app",MergeEngine.APP).put("mergeProtocol",3).put("expectedRevision",receiver.getLong("revision")).put("records",sender.getJSONArray("records")).put("pages",sender.getJSONArray("pages"));}
 private void work(boolean commit){if(busy)return;busy=true;preview.setEnabled(false);merge.setEnabled(false);status.setText(commit?"正在备份并合并，请保持连接…":"正在读取双方数据…");new Thread(()->{try{if(!LedgerService.running)throw new IOException("本机服务正在启动，请稍后重试");if(!commit){lt=login(base,LedgerService.code);rt=login(remoteBase,remoteCode);local=request(base,"/api/state",lt,null);remote=request(remoteBase,"/api/state",rt,null);check(local);check(remote);MergeEngine.Plan a=MergeEngine.plan(local.getJSONArray("records"),remote.getJSONArray("records")),b=MergeEngine.plan(remote.getJSONArray("records"),local.getJSONArray("records"));int localPages=Workspaces.union(local.getJSONArray("pages"),remote.getJSONArray("pages")).length()-local.getJSONArray("pages").length(),remotePages=Workspaces.union(remote.getJSONArray("pages"),local.getJSONArray("pages")).length()-remote.getJSONArray("pages").length();String text="本机新增工作表 "+localPages+" 个；对方新增工作表 "+remotePages+" 个\n本机新增 "+a.additions.length()+" 条（冲突副本 "+a.conflicts+"）\n对方新增 "+b.additions.length()+" 条（冲突副本 "+b.conflicts+"）\n同编号工作表名称保留各自命名；照片随记录合并。不同编号的相似记录不会自动认定为同一条。";runOnUiThread(()->{status.setText(text);merge.setEnabled(true);});}else{remoteApplied=false;request(remoteBase,"/api/merge",rt,payload(remote,local));remoteApplied=true;request(base,"/api/merge",lt,payload(local,remote));runOnUiThread(()->{status.setText("双方合并完成。可以断开热点，各自继续编辑本机数据。以后需再次扫码合并。\n冲突副本请核对后手动删除或确认。");preview.setEnabled(false);});remoteBase=null;if(getIntent().getBooleanExtra("disconnect",false))stopService(new Intent(this,ClientService.class));}}catch(Exception e){String message=(commit?(remoteApplied?"对方已完成合并，本机未确认完成；":"对方可能已收到数据；")+"请重新预览后重试，重复内容会去重。\n":"")+e.getMessage();runOnUiThread(()->status.setText(message));}finally{runOnUiThread(()->{busy=false;preview.setEnabled(remoteBase!=null);});}},"one-time-merge").start();}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==21&&result==RESULT_OK&&data!=null&&exportFile!=null)try(InputStream in=new FileInputStream(exportFile);OutputStream out=getContentResolver().openOutputStream(data.getData())){byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);status.setText("备份已导出。恢复时可在本机页面导入备份，采用追加方式。");}catch(Exception e){status.setText("导出失败，请重试");}}
 public void onBackPressed(){if(busy){Toast.makeText(this,"正在合并，请稍候",Toast.LENGTH_SHORT).show();return;}super.onBackPressed();}
 protected void onDestroy(){if(isFinishing()&&!busy&&getIntent().getBooleanExtra("disconnect",false))stopService(new Intent(this,ClientService.class));super.onDestroy();}
}
