package app.triprank;
import android.app.*;import android.content.*;import android.os.*;import android.graphics.*;import android.hardware.Camera;import android.view.*;import android.widget.*;import com.google.zxing.*;import com.google.zxing.common.*;import java.util.*;import java.util.concurrent.*;
@SuppressWarnings("deprecation")
public class ScanActivity extends Activity implements SurfaceHolder.Callback {
 private SurfaceView surface;private Camera camera;private boolean surfaceReady,active;private volatile boolean decoding=false,done=false;private long lastFrame;private final ExecutorService executor=Executors.newSingleThreadExecutor();private TextView hint;
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(12,48,12,32);root.setBackgroundColor(Color.rgb(24,26,40));setContentView(root);hint=new TextView(this);hint.setText("扫描主机的加入二维码\n无需输入热点密码或访问码");hint.setTextColor(Color.WHITE);hint.setTextSize(18);hint.setPadding(14,18,14,18);root.addView(hint);surface=new SurfaceView(this);root.addView(surface,new LinearLayout.LayoutParams(-1,0,1));surface.getHolder().addCallback(this);Button gallery=new Button(this);gallery.setText("从相册识别二维码");gallery.setOnClickListener(v->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),2));root.addView(gallery);Button cancel=new Button(this);cancel.setText("取消");cancel.setOnClickListener(v->finish());root.addView(cancel);if(checkSelfPermission("android.permission.CAMERA")!=0)requestPermissions(new String[]{"android.permission.CAMERA"},1);}
 public void onResume(){super.onResume();active=true;openCamera();}public void onPause(){active=false;release();super.onPause();}public void onDestroy(){executor.shutdownNow();super.onDestroy();}
 public void onRequestPermissionsResult(int c,String[] p,int[] r){super.onRequestPermissionsResult(c,p,r);if(c==1){if(r.length>0&&r[0]==0)openCamera();else hint.setText("未允许相机，可点击下方从相册识别二维码。");}}
 public void surfaceCreated(SurfaceHolder h){surfaceReady=true;openCamera();}public void surfaceChanged(SurfaceHolder h,int f,int w,int v){}public void surfaceDestroyed(SurfaceHolder h){surfaceReady=false;release();}
 private void openCamera(){if(!active||!surfaceReady||camera!=null||done||checkSelfPermission("android.permission.CAMERA")!=0)return;try{int index=0;Camera.CameraInfo info=new Camera.CameraInfo();for(int i=0;i<Camera.getNumberOfCameras();i++){Camera.getCameraInfo(i,info);if(info.facing==Camera.CameraInfo.CAMERA_FACING_BACK){index=i;break;}}Camera.getCameraInfo(index,info);camera=Camera.open(index);Camera.Parameters p=camera.getParameters();Camera.Size chosen=null;for(Camera.Size z:p.getSupportedPreviewSizes())if(z.width<=1280&&(chosen==null||Math.abs(z.width-640)<Math.abs(chosen.width-640)))chosen=z;if(chosen!=null)p.setPreviewSize(chosen.width,chosen.height);p.setPreviewFormat(ImageFormat.NV21);List<String> modes=p.getSupportedFocusModes();if(modes.contains(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE))p.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE);else if(modes.contains(Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO))p.setFocusMode(Camera.Parameters.FOCUS_MODE_CONTINUOUS_VIDEO);camera.setParameters(p);int degrees=getWindowManager().getDefaultDisplay().getRotation()*90;camera.setDisplayOrientation((info.orientation-degrees+360)%360);camera.setPreviewDisplay(surface.getHolder());camera.setPreviewCallback((bytes,c)->{if(done||decoding||System.currentTimeMillis()-lastFrame<250)return;lastFrame=System.currentTimeMillis();decoding=true;Camera.Size z=c.getParameters().getPreviewSize();byte[] data=bytes.clone();executor.execute(()->{try{decode(new PlanarYUVLuminanceSource(data,z.width,z.height,0,0,z.width,z.height,false));}catch(Exception ignored){}finally{decoding=false;}});});camera.startPreview();}catch(Exception e){release();hint.setText("无法打开相机，可从相册识别二维码。" );}}
 private void release(){if(camera!=null){try{camera.setPreviewCallback(null);camera.stopPreview();camera.release();}catch(Exception ignored){}camera=null;}}
 private void decode(LuminanceSource luminance)throws Exception{Map<DecodeHintType,Object> hints=new EnumMap<>(DecodeHintType.class);hints.put(DecodeHintType.POSSIBLE_FORMATS,Collections.singletonList(BarcodeFormat.QR_CODE));hints.put(DecodeHintType.TRY_HARDER,true);String text=new MultiFormatReader().decode(new BinaryBitmap(new HybridBinarizer(luminance)),hints).getText();try{Invite.parse(text);}catch(Exception e){runOnUiThread(()->hint.setText("不是有效的旅途排排榜邀请，请扫描主机显示的二维码。"));return;}if(done)return;done=true;runOnUiThread(()->{if(!isFinishing()){setResult(RESULT_OK,new Intent().putExtra("invite",text));finish();}});}
 protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==2&&result==RESULT_OK&&data!=null){executor.execute(()->{try{BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;try(java.io.InputStream in=getContentResolver().openInputStream(data.getData())){BitmapFactory.decodeStream(in,null,options);}int sample=1;while(Math.max(options.outWidth,options.outHeight)/sample>1800)sample*=2;options.inSampleSize=sample;options.inJustDecodeBounds=false;Bitmap image;try(java.io.InputStream in=getContentResolver().openInputStream(data.getData())){image=BitmapFactory.decodeStream(in,null,options);}if(image==null)throw new Exception();int w=image.getWidth(),h=image.getHeight();int[] pixels=new int[w*h];image.getPixels(pixels,0,w,0,0,w,h);image.recycle();decode(new RGBLuminanceSource(w,h,pixels));}catch(Exception e){runOnUiThread(()->hint.setText("未识别到二维码，请选择清晰、完整的二维码图片。"));}});}}
}
