package app.triprank;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.graphics.Color;import android.webkit.*;import android.view.*;import android.widget.*;import java.io.*;import java.net.URI;import java.nio.charset.StandardCharsets;import java.util.*;import org.json.*;
/** In-app working screen. File access uses Android's user-directed document picker. */
public class WebActivity extends Activity {
 private WebView web;private String entry,origin;private ValueCallback<Uri[]> chooser;private File pendingExport;private volatile boolean exporting=false;private TextView status;private Button retry;
 public static void open(Activity source,String url){source.startActivity(new Intent(source,WebActivity.class).putExtra("url",url).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));}
 private int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 public void onCreate(Bundle saved){super.onCreate(saved);try{entry=getIntent().getStringExtra("url");origin=allowedOrigin(entry);}catch(Exception e){new AlertDialog.Builder(this).setMessage("页面地址无效，请返回首页重新扫码。").setPositiveButton("返回",(d,w)->finish()).show();return;}
  if(Build.VERSION.SDK_INT>=33)getOnBackInvokedDispatcher().registerOnBackInvokedCallback(0,()->onBackPressed());
  LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(Color.WHITE);setContentView(root);root.setOnApplyWindowInsetsListener((v,i)->{root.setPadding(0,i.getSystemWindowInsetTop(),0,i.getSystemWindowInsetBottom());return i;});LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);bar.setPadding(dp(6),0,dp(6),0);root.addView(bar,new LinearLayout.LayoutParams(-1,dp(52)));Button home=new Button(this);home.setText("首页");home.setOnClickListener(v->leave());bar.addView(home,new LinearLayout.LayoutParams(dp(76),-1));status=new TextView(this);status.setText("旅途排排榜");status.setTextSize(15);status.setPadding(dp(10),0,0,0);bar.addView(status,new LinearLayout.LayoutParams(0,-2,1));Button reconnect=new Button(this);reconnect.setText("重连");reconnect.setOnClickListener(v->{new AlertDialog.Builder(this).setMessage("重连会重新加载页面，请先保存正在编辑的内容。") .setNegativeButton("取消",null).setPositiveButton("重连",(d,w)->{if(LedgerService.running&&origin.equals("http://127.0.0.1:8766")){entry="http://127.0.0.1:8766/#join="+LedgerService.code;web.loadUrl(entry);}else startActivity(new Intent(this,JoinActivity.class));}).show();});bar.addView(reconnect,new LinearLayout.LayoutParams(dp(76),-1));
  retry=new Button(this);retry.setText("页面加载失败，点此重试；也可点右上角重新连接");retry.setVisibility(View.GONE);retry.setOnClickListener(v->web.loadUrl(entry));root.addView(retry);web=new WebView(this);root.addView(web,new LinearLayout.LayoutParams(-1,0,1));WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(true);settings.setAllowFileAccessFromFileURLs(false);settings.setAllowUniversalAccessFromFileURLs(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setSupportMultipleWindows(false);web.addJavascriptInterface(new FilesBridge(),"NativeFiles");
  web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){return !sameOrigin(request.getUrl().toString());}public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){String scheme=request.getUrl().getScheme();if(("http".equals(scheme)||"https".equals(scheme))&&!sameOrigin(request.getUrl().toString()))return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));return null;}public void onPageStarted(WebView v,String u,android.graphics.Bitmap icon){retry.setVisibility(View.GONE);status.setText("正在加载…");}public void onPageFinished(WebView v,String u){status.setText("旅途排排榜");}public void onReceivedError(WebView v,WebResourceRequest req,WebResourceError e){if(req.isForMainFrame()){status.setText("连接未就绪");retry.setVisibility(View.VISIBLE);}}});
  web.setWebChromeClient(new WebChromeClient(){public boolean onJsAlert(WebView v,String u,String message,JsResult result){new AlertDialog.Builder(WebActivity.this).setMessage(message).setPositiveButton("知道了",(d,w)->result.confirm()).setOnCancelListener(d->result.cancel()).show();return true;}public boolean onJsConfirm(WebView v,String u,String message,JsResult result){new AlertDialog.Builder(WebActivity.this).setMessage(message).setPositiveButton("确定",(d,w)->result.confirm()).setNegativeButton("取消",(d,w)->result.cancel()).setOnCancelListener(d->result.cancel()).show();return true;}
   public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> callback,FileChooserParams params){if(chooser!=null)chooser.onReceiveValue(null);chooser=callback;Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE);boolean image=false,json=false;for(String type:params.getAcceptTypes()){if(type!=null){image|=type.contains("image")||type.contains(".jpg")||type.contains(".png");json|=type.contains("json");}}pick.setType(image&&!json?"image/*":json&&!image?"application/json":"*/*");pick.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,params.getMode()==FileChooserParams.MODE_OPEN_MULTIPLE);try{startActivityForResult(pick,41);}catch(Exception e){chooser.onReceiveValue(null);chooser=null;Toast.makeText(WebActivity.this,"系统文件选择器不可用",Toast.LENGTH_LONG).show();}return true;}
  });web.loadUrl(entry);
 }
 private String allowedOrigin(String address)throws Exception{URI uri=new URI(address);String host=uri.getHost();if(!"http".equals(uri.getScheme())||host==null||uri.getRawUserInfo()!=null||uri.getPort()<1||uri.getPort()>65535)throw new Exception();if(!host.equals("127.0.0.1")){Invite invite=new Invite();invite.url="http://"+host+":"+uri.getPort();invite.code="ABCDEF12";invite.validate();}return "http://"+host+":"+uri.getPort();}
 private boolean sameOrigin(String address){try{return origin.equals(allowedOrigin(address));}catch(Exception e){return false;}}
 protected void onNewIntent(Intent intent){super.onNewIntent(intent);String next=intent.getStringExtra("url");if(next==null||web==null)return;try{String nextOrigin=allowedOrigin(next);entry=next;origin=nextOrigin;web.loadUrl(entry);setIntent(intent);}catch(Exception e){Toast.makeText(this,"无效的页面地址",Toast.LENGTH_SHORT).show();}}
 public class FilesBridge {@JavascriptInterface public String syncStatus(){return AutoSync.status;}@JavascriptInterface public String getIdentity(String previousName){return IdentityStore.get(WebActivity.this,previousName);}@JavascriptInterface public String selectIdentity(String name){return IdentityStore.select(WebActivity.this,name);}@JavascriptInterface public void saveBackup(String json,String filename){if(exporting)return;exporting=true;try{byte[] bytes=json.getBytes(StandardCharsets.UTF_8);if(bytes.length>64*1024*1024)throw new Exception("备份超过 64MB");JSONObject content=new JSONObject(json);if(!"trip-rank".equals(content.optString("app")))throw new Exception("备份格式不正确");File temp=File.createTempFile("backup-",".json",getCacheDir());try(FileOutputStream out=new FileOutputStream(temp)){out.write(bytes);}pendingExport=temp;String title=filename==null?"旅途排排榜备份.json":filename.replaceAll("[\\\\/:*?\"<>|\\p{Cntrl}]","_");if(title.length()>100)title="旅途排排榜备份.json";final String safeName=title;runOnUiThread(()->{if(isFinishing()){cleanExport();return;}try{startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("application/json").putExtra(Intent.EXTRA_TITLE,safeName),42);}catch(Exception e){cleanExport();Toast.makeText(WebActivity.this,"无法打开系统保存窗口",Toast.LENGTH_LONG).show();}});}catch(Exception e){cleanExport();runOnUiThread(()->Toast.makeText(WebActivity.this,"备份失败："+e.getMessage(),Toast.LENGTH_LONG).show());}}}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==41){ValueCallback<Uri[]> callback=chooser;chooser=null;if(callback==null)return;if(result!=RESULT_OK||data==null){callback.onReceiveValue(null);return;}ArrayList<Uri> urls=new ArrayList<>();if(data.getClipData()!=null)for(int i=0;i<data.getClipData().getItemCount();i++)urls.add(data.getClipData().getItemAt(i).getUri());else if(data.getData()!=null)urls.add(data.getData());callback.onReceiveValue(urls.isEmpty()?null:urls.toArray(new Uri[0]));}else if(request==42){if(result!=RESULT_OK||data==null||pendingExport==null){cleanExport();return;}final Uri destination=data.getData();final File source=pendingExport;new Thread(()->{String message;try(InputStream in=new FileInputStream(source);OutputStream out=getContentResolver().openOutputStream(destination,"wt")){if(out==null)throw new IOException();byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);message="备份已保存";}catch(Exception e){message="备份保存失败，请重新导出";}cleanExport();final String text=message;runOnUiThread(()->Toast.makeText(WebActivity.this,text,Toast.LENGTH_LONG).show());},"backup-save").start();}}
 private void cleanExport(){if(pendingExport!=null){pendingExport.delete();pendingExport=null;}exporting=false;}
 private void leave(){if(web==null){finish();return;}web.evaluateJavascript("(()=>{try{return (typeof dirty!=='undefined'&&dirty)||!!document.querySelector('#editor[open]')}catch(e){return false}})()",value->{if("true".equals(value))new AlertDialog.Builder(this).setMessage("返回首页将关闭当前编辑页面，请先保存。仍要返回吗？").setNegativeButton("继续编辑",null).setPositiveButton("返回",(d,w)->home()).show();else home();});}
 private void home(){startActivity(new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));finish();}
 @Override public void onBackPressed(){if(web==null){finish();return;}web.evaluateJavascript("(()=>{const ds=[...document.querySelectorAll('dialog[open]')];if(!ds.length)return false;const d=ds[ds.length-1];if(d.id==='login')return false;const e=new Event('cancel',{cancelable:true});if(d.dispatchEvent(e))d.close();return true})()",value->{if(!"true".equals(value))leave();});}
 protected void onDestroy(){if(chooser!=null){chooser.onReceiveValue(null);chooser=null;}if(web!=null){web.removeJavascriptInterface("NativeFiles");web.destroy();}if(!exporting)cleanExport();super.onDestroy();}
}
