package app.triprank;
import org.json.*;import java.util.*;
final class Workspaces {
 static String of(JSONObject r){return r.optString("workspace","default");}
 static JSONArray defaults()throws Exception{return new JSONArray().put(new JSONObject().put("id","default").put("name","默认工作表"));}
 static JSONArray validate(JSONArray pages)throws Exception{if(pages==null||pages.length()>200)throw new LocalServer.Problem(400,"工作表最多 200 个");Set<String> ids=new HashSet<>();JSONArray clean=new JSONArray();for(int i=0;i<pages.length();i++){JSONObject p=pages.getJSONObject(i);Object id=p.opt("id"),name=p.opt("name");if(!(id instanceof String)||!((String)id).matches("[A-Za-z0-9_-]{1,100}")||!(name instanceof String)||((String)name).trim().isEmpty()||((String)name).length()>40||!ids.add((String)id))throw new LocalServer.Problem(400,"工作表格式错误");clean.put(new JSONObject().put("id",id).put("name",((String)name).trim()));}return clean;}
 static boolean has(JSONArray pages,String id)throws Exception{for(int i=0;i<pages.length();i++)if(pages.getJSONObject(i).getString("id").equals(id))return true;return false;}
 static JSONArray union(JSONArray a,JSONArray b)throws Exception{JSONArray result=new JSONArray(a.toString());for(int i=0;i<b.length();i++){JSONObject p=b.getJSONObject(i);if(!has(result,p.getString("id")))result.put(p);}return validate(result);}
 static JSONArray ids(JSONObject r){JSONArray ids=r.optJSONArray("workspaceIds");return ids!=null?ids:new JSONArray().put(of(r));}
 static boolean includes(JSONObject r,String page){JSONArray a=ids(r);for(int i=0;i<a.length();i++)if(page.equals(a.optString(i)))return true;return false;}
 static JSONObject position(JSONObject r,String page){JSONObject all=r.optJSONObject("placements"),pos=all==null?null:all.optJSONObject(page);if(pos!=null)return pos;try{return new JSONObject().put("tier",of(r).equals(page)?r.optString("tier","pending"):"pending").put("rank",of(r).equals(page)?r.optLong("rank",0):0);}catch(Exception e){throw new IllegalArgumentException(e);}}
 static String tier(JSONObject r,String page){return position(r,page).optString("tier","pending");}
 static long rank(JSONObject r,String page){return position(r,page).optLong("rank",0);}
 static void set(JSONObject r,String page,String tier,long rank)throws Exception{JSONObject positions=r.optJSONObject("placements");if(positions==null){positions=new JSONObject();JSONArray a=ids(r);for(int i=0;i<a.length();i++){String id=a.getString(i);positions.put(id,position(r,id));}}positions.put(page,new JSONObject().put("tier",tier).put("rank",rank));r.put("placements",positions);if(of(r).equals(page))r.put("tier",tier).put("rank",rank);}
 static void select(JSONObject r,JSONArray selected)throws Exception{JSONObject positions=new JSONObject();for(int i=0;i<selected.length();i++){String id=selected.getString(i);positions.put(id,position(r,id));}r.put("workspaceIds",selected).put("placements",positions);String first=selected.length()>0?selected.getString(0):"default";r.put("workspace",first).put("tier",selected.length()>0?tier(r,first):"pending").put("rank",selected.length()>0?rank(r,first):0);}
 static void validateRecord(JSONObject raw,JSONObject clean)throws Exception{JSONArray selected=raw.has("workspaceIds")?raw.optJSONArray("workspaceIds"):new JSONArray().put(of(clean));if(selected==null||selected.length()>200)throw new LocalServer.Problem(400,"工作表选择格式错误");Set<String> unique=new HashSet<>();JSONObject positions=new JSONObject();for(int i=0;i<selected.length();i++){Object v=selected.opt(i);if(!(v instanceof String)||!((String)v).matches("[A-Za-z0-9_-]{1,100}")||!unique.add((String)v))throw new LocalServer.Problem(400,"工作表编号错误");String id=(String)v;JSONObject pos=position(raw,id);Object rank=pos.opt("rank");if(!LocalServer.TIERS.contains(pos.optString("tier"))||!(rank instanceof Number)||((Number)rank).doubleValue()<0||((Number)rank).doubleValue()>1e12||!Double.isFinite(((Number)rank).doubleValue()))throw new LocalServer.Problem(400,"工作表排名错误");positions.put(id,new JSONObject().put("tier",pos.getString("tier")).put("rank",((Number)rank).longValue()));}if(raw.has("placements")&&!(raw.opt("placements") instanceof JSONObject))throw new LocalServer.Problem(400,"排名格式错误");clean.put("workspaceIds",selected).put("placements",positions);}
 static void checkRecords(JSONArray pages,JSONArray records)throws Exception{for(int i=0;i<records.length();i++){JSONArray selected=ids(records.getJSONObject(i));for(int j=0;j<selected.length();j++)if(!has(pages,selected.getString(j)))throw new LocalServer.Problem(400,"项目引用的工作表不存在，请刷新后重试");}}
 static long nextRank(LocalServer.Store store,String page,String tier)throws Exception{long rank=0;JSONArray all=store.all();for(int i=0;i<all.length();i++){JSONObject r=all.getJSONObject(i);if(includes(r,page)&&tier(r,page).equals(tier))rank=Math.max(rank,rank(r,page)+1);}return rank;}
}
